version: '3.8'

services:
  # Cơ sở dữ liệu PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: toanthaycong_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: toanthaycong
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d
    networks:
      - toanthaycong_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ứng dụng Go
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: toanthaycong_app
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USER=postgres
  #     - DB_PASSWORD=password123
  #     - DB_NAME=toanthaycong
  #     - DB_SSL_MODE=disable
  #     - APP_ENV=development
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - toanthaycong_network
  #   volumes:
  #     - .:/app
  #   working_dir: /app

  # pgAdmin (Tùy chọn - để quản lý database)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: toanthaycong_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - toanthaycong_network

volumes:
  postgres_data:
    driver: local

networks:
  toanthaycong_network:
    driver: bridge
